apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-lb
  labels:
    app:  {{ .Values.appName }}
spec:
  selector:
    app:  {{ .Values.appName }}-lb
  ports:
    - port: 80
      protocol: TCP
      targetPort: 15672
  type: LoadBalancer
  
