apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.service.name }}
  labels:
    app:  {{ .Values.appName }}

spec:
  type: ClusterIP
  selector:
    app:  {{ .Values.appName }}
  ports:
    - name: http
      port: 15672
      targetPort: 15672
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
