apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}

spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  serviceName: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: rabbitmq-container
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amq
              protocol: TCP
              containerPort: 5672
          envFrom:
          - configMapRef:
              name: {{ .Values.configmap.name }}
          - secretRef:
              name: {{ .Values.secret.name }}
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-volume
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-pvc